# Generated by Django 2.2.3 on 2019-07-31 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='picture',
            new_name='article',
        ),
    ]
